### ISSUE TITLE
Lightning grenade and lightning bomb do not produce lightning

### ISSUE THREAD

**Issue by Beanlord002** [rubensworks/EvilCraft#906]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When a lightning grenade is thrown or a lightning bomb explodes, no lightning is summoned. I tested it without other mods (other than cyclopscore 1.12.2) as well as with the other mods present in my modpack with the same results. The grenade gives off little star particles and the bomb just creates a very small explosion.

#### Steps to reproduce the problem:

1. Install the shown versions of EvilCraft and run minecraft
2. Throw a lightning grenade or set off a lightning bomb and let it explode

#### Expected behaviour:

A lightning strike on the block where the grenade landed / where the bomb exploded
____

#### Versions:

- This mod: 1.1.14 and 1.1.15 (tested for both)
- Minecraft: 1.16.5
- Forge: 36.2.30

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Should have been fixed a while ago.

**Comment by Surferblue** [comment]
I still have this bug.
Versions:
This mod: 1.1.17 
Minecraft: 1.16.5
Forge: 36.2.39

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.16 is not supported anymore.
